project:
  type: website
  output-dir: docs

website:
  title: "Analysing High Throughput Sequencing Data"
  navbar:
    logo: "images/logo.png"
    left:
      - text: "Home"
        href: 2024_chip_workshop.qmd
      - text: "Processing"
        href: ChIP-seq_workshop_processing.qmd
      - text: "Analysis"
        href: ChIP-seq_workshop_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual